#!/usr/bin/env python3

from functools import reduce
from os import path
from glob import glob
import re
import argparse
from typing import List, Tuple, Union
import multiprocessing as mp
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib


def parse_arguments() -> argparse.Namespace:
    """A function for parsing the command line arguments outside of the main function.
    Signals conflicts among command line options."""

    parser = argparse.ArgumentParser(
        description="""A script for the parsing of output generated by VIBRANT""",
    )
    parser.add_argument(
        "-i",
        "--input_dir",
        help="""An output directory produced by VIBRANT, or a directory that contains multiple VIBRANT output directories""",
        required=True,
    )

    parser.add_argument(
        "-o", "--output", help="""Summary file produced by this script"""
    )

    parser.add_argument(
        "-f",
        "--force",
        action="store_true",
        help="""Overwrite output file if present""",
    )

    parser.add_argument(
        "-m",
        "--multiple_directories",
        action="store_true",
        help="""Select this option if the input directory contains more than one VIBRANT output directory""",
    )

    parser.add_argument(
        "-t",
        "--threads",
        type=int,
        default=None,
        help="""Number of processors used when working on multiple directories.
                        Defaults to the number of cpu cores.""",
    )

    args = parser.parse_args()

    if not path.isdir(args.input_dir):
        raise Exception(
            "Input argument {} is not a directory".format(args.input_dir)
        )

    args.input_dir = path.normpath(args.input_dir)

    if not args.multiple_directories and not path.basename(
        args.input_dir
    ).startswith("VIBRANT_"):
        print(
            "Warning: input directory {} does not start with the prefix VIBRANT_".format(
                args.input_dir
            )
        )

    if not args.multiple_directories and args.threads is not None:
        print(
            """Warning: the --threads option has been selected with {} cores, but this script has been launched on a single directory.
        If you plan to analyze multiple directories, please select the -m / --multiple_directories option""".format(
                args.threads
            )
        )

    if args.output is None:
        if args.multiple_directories:
            args.output = args.input_dir + "_multiple_summary.txt"
        else:
            args.output = args.input_dir + "_summary.txt"

    if path.isfile(args.output) and not args.force:
        raise Exception(
            """Output file {} already exists.
                        Specify -f or --force to overwrite it""".format(
                args.output
            )
        )

    return args


def find_vibrant_log(vibrant_output_dir: str) -> str:
    """A function to find the run log of the VIBRANT output directory.
    Ensures there is one and only one run log file."""

    glob_files = glob(path.join(vibrant_output_dir, "VIBRANT_log_run*.log"))

    if len(glob_files) < 1:
        raise Exception(
            "No log file was found in the VIBRANT output directory {}".format(
                vibrant_output_dir
            )
        )

    if len(glob_files) > 1:
        raise Exception(
            "More than one log file was found in the VIBRANT output directory {}".format(
                vibrant_output_dir
            )
        )

    return glob_files[0]


def parse_vibrant_log(vibrant_log_file: str) -> dict:
    """Parse the run log file to retrieve info about the number of scaffolds"""

    dct = {
        "scaffolds read": None,
        "scaffolds with minimum requirements": None,
        "putative phages": None,
    }

    with open(vibrant_log_file) as f:
        for line in f:
            match_scaffolds_read = re.match(
                r"([0-9]+) scaffolds were read in", line
            )
            match_scaffolds_min_req = re.match(
                r"([0-9]+) scaffolds met minimum requirements", line
            )
            match_putative_phages = re.match(r"([0-9]+) putative phages", line)

            if match_scaffolds_read:
                dct["scaffolds read"] = int(match_scaffolds_read.group(1))

            if match_scaffolds_min_req:
                dct["scaffolds with minimum requirements"] = int(
                    match_scaffolds_min_req.group(1)
                )

            if match_putative_phages:
                dct["putative phages"] = int(match_putative_phages.group(1))

    return dct


def find_types_quality_file(vibrant_output_dir: str) -> str:
    glob_files = glob(
        path.join(
            vibrant_output_dir,
            "VIBRANT_results*",
            "VIBRANT_genome_quality_*.tsv",
        )
    )

    if len(glob_files) < 1:
        raise Exception(
            """VIBRANT_gene_quality_ file was not found in directory {}.
                        It is supposed to be in the VIBRANT_results subdirectory""".format(
                vibrant_output_dir
            )
        )

    if len(glob_files) > 1:
        raise Exception(
            """More than one VIBRANT_gene_quality_ file was found in the VIBRANT output directory {}""".format(
                vibrant_output_dir
            )
        )

    return glob_files[0]


def parse_types_quality(types_quality_file) -> dict:
    dct = {
        "fragment": 0,
        "low quality draft": 0,
        "medium quality draft": 0,
        "high quality draft": 0,
        "complete circular": 0,
        "lytic": 0,
        "lysogenic": 0,
    }

    df = pd.read_table(types_quality_file)
    dct.update(df.groupby("type").count()["scaffold"].to_dict())
    dct.update(df.groupby("Quality").count()["scaffold"].to_dict())

    return dct


def find_amg_file(vibrant_output_dir: str) -> str:
    glob_files = glob(
        path.join(
            vibrant_output_dir, "VIBRANT_results_*", "VIBRANT_AMG_counts_*.tsv"
        )
    )

    if len(glob_files) < 1:
        raise Exception(
            """VIBRANT_AMG_counts_ file was not found in directory {}.
                        It is supposed to be in the VIBRANT_results subdirectory""".format(
                vibrant_output_dir
            )
        )

    if len(glob_files) > 1:
        raise Exception(
            """More than one VIBRANT_AMG_counts_ file was found in the VIBRANT output directory {}""".format(
                vibrant_output_dir
            )
        )

    return glob_files[0]


def find_pathway_file(vibrant_output_dir: str) -> str:
    glob_files = glob(
        path.join(
            vibrant_output_dir,
            "VIBRANT_results_*",
            "VIBRANT_AMG_pathways_*.tsv",
        )
    )

    if len(glob_files) < 1:
        raise Exception(
            """VIBRANT_AMG_pathways_ file was not found in directory {}.
                        It is supposed to be in the VIBRANT_results subdirectory""".format(
                vibrant_output_dir
            )
        )

    if len(glob_files) > 1:
        raise Exception(
            """More than one VIBRANT_AMG_pathways_ file was found in the VIBRANT output directory {}""".format(
                vibrant_output_dir
            )
        )

    return glob_files[0]


def find_counts_file(vibrant_output_dir: str) -> str:
    glob_files = glob(
        path.join(
            vibrant_output_dir, "VIBRANT_results_*", "VIBRANT_AMG_counts_*.tsv"
        )
    )

    if len(glob_files) < 1:
        raise Exception(
            """VIBRANT_AMG_counts_ file was not found in directory {}.
                        It is supposed to be in the VIBRANT_results subdirectory""".format(
                vibrant_output_dir
            )
        )

    if len(glob_files) > 1:
        raise Exception(
            """More than one VIBRANT_AMG_counts_ file was found in the VIBRANT output directory {}""".format(
                vibrant_output_dir
            )
        )

    return glob_files[0]


def find_individual_file(vibrant_output_dir: str) -> str:
    glob_files = glob(
        path.join(
            vibrant_output_dir,
            "VIBRANT_results_*",
            "VIBRANT_AMG_individuals_*.tsv",
        )
    )

    if len(glob_files) < 1:
        raise Exception(
            """VIBRANT_AMG_individuals_ file was not found in directory {}.
                        It is supposed to be in the VIBRANT_results subdirectory""".format(
                vibrant_output_dir
            )
        )

    if len(glob_files) > 1:
        raise Exception(
            """More than one VIBRANT_AMG_individuals_ file was found in the VIBRANT output directory {}""".format(
                vibrant_output_dir
            )
        )

    return glob_files[0]


def plot_pathways(pathway_files: List[str]):
    dataframes = [pd.read_table(file) for file in pathway_files]


def parse_amgs(amg_file: str) -> dict:
    """Retrieves the total number of AMGs of a single directory"""
    df = pd.read_table(amg_file)

    sample_amgs = len(df)
    total_amgs = df["AMG count"].sum()

    return {"sample amgs": sample_amgs, "total amgs": total_amgs}


def parse_single_directory(
    vibrant_dir: str,
    output_file: Union[str, None] = None,
) -> Tuple[str, dict]:
    """Manages the flow regarding a single directory.
    Saves the statistics into a single file.
    Reurns the name of the directory and a dictionary gathering the statistics
    """

    sample = path.basename(vibrant_dir).replace("VIBRANT_", "")
    # print(f"{sample=}")

    if output_file is None:
        output_file = vibrant_dir + "_summary.txt"

    data = {}

    vibrant_log = find_vibrant_log(vibrant_dir)
    types_quality_file = find_types_quality_file(vibrant_dir)
    amg_file = find_amg_file(vibrant_dir)

    data.update(parse_types_quality(types_quality_file))
    data.update(parse_vibrant_log(vibrant_log))
    data.update(parse_amgs(amg_file))

    series = pd.Series(data, name=sample)
    series.to_csv(output_file, sep="\t")

    return sample, data


def find_output_directories(dir: str) -> List[str]:
    """Used when the -m/--multiple_directories option is used.
    Retrieves all the VIBRANT output directories in the given directory. Ensures that there is at least one.
    """

    dirs = [x for x in glob(path.join(dir, "VIBRANT_*")) if path.isdir(x)]

    if len(dirs) == 0:
        raise Exception(
            "No VIBRANT output directories found in directory {}".format(dir)
        )

    return dirs


def amg_per_scaffold(vibrant_output_dir: str) -> pd.DataFrame:
    sample = path.basename(vibrant_output_dir).replace("VIBRANT_", "")

    pathway_file = find_pathway_file(vibrant_output_dir)
    individual_file = find_individual_file(vibrant_output_dir)

    pathway_df = pd.read_table(pathway_file)
    individual_df = pd.read_table(individual_file)

    pathway_df["Present AMG KOs set"] = (
        pathway_df["Present AMG KOs"].str.split(",").apply(set)
    )

    indv_df_by_scaffold = individual_df.groupby("scaffold").agg(set)["AMG KO"]

    pathway_df[sample] = pathway_df["Present AMG KOs set"].apply(
        lambda x: indv_df_by_scaffold.apply(
            lambda y: bool(y.intersection(x))
        ).sum()
    )

    return pathway_df[["KEGG Entry", "Metabolism", "Pathway", sample]]


def merge_two_dfs(left: pd.DataFrame, right: pd.DataFrame) -> pd.DataFrame:
    return pd.merge(
        left, right, how="outer", on=["KEGG Entry", "Metabolism", "Pathway"]
    ).fillna(0)


def calculate_positions(metabolism_label_df: pd.DataFrame, column: str) -> List:
    positions = []

    for i in range(metabolism_label_df.shape[0]):
        if i == 0:
            pos = metabolism_label_df[column].iloc[i] / 2
        else:
            pos = (
                metabolism_label_df["cumulative sum"].iloc[i - 1]
                + metabolism_label_df[column].iloc[i] / 2
            )
        positions.append(pos - 0.5)

    return positions


def metabolism_df(df: pd.DataFrame, column: str) -> pd.DataFrame:
    metabolism_label_df = (
        df.groupby("Metabolism").count()[[column]].sort_index(ascending=False)
    )

    metabolism_label_df["cumulative sum"] = metabolism_label_df[column].cumsum()

    metabolism_label_df["position"] = calculate_positions(
        metabolism_label_df, column
    )

    metabolism_label_df["color"] = np.arange(metabolism_label_df.shape[0])

    return metabolism_label_df


def pathway_map(
    df: pd.DataFrame, metabolism_df: pd.DataFrame
) -> matplotlib.figure.Figure:
    only_samples = df.drop(
        columns=["KEGG Entry", "Metabolism", "Pathway", "color"]
    ).astype(int)

    perc_amgs_per_sample = only_samples / only_samples.sum()

    fig, (ax_1, ax_2) = plt.subplots(
        1,
        2,
        figsize=((df.shape[1] + 1) / 2, df.shape[0] / 2),
        gridspec_kw={"width_ratios": (1, df.shape[1])},
        squeeze=True,
    )

    ax_1.pcolormesh(df[["color"]], cmap="Paired_r")
    ax_1.set_yticks(metabolism_df["position"] + 0.5)
    ax_1.set_yticklabels(metabolism_df.index)
    ax_1.get_xaxis().set_visible(False)

    im = ax_2.pcolormesh(
        perc_amgs_per_sample,
        cmap="GnBu",
    )

    ax_2.set_title(
        "Nr. of viral scaffolds",
        fontdict={"fontsize": "xx-large"},
    )

    ax_2.xaxis.tick_top()
    ax_2.yaxis.tick_right()

    ax_2.set_xticks(np.arange(only_samples.shape[1]) + 0.5)
    ax_2.set_xticklabels(only_samples.columns, rotation=45, ha="left")

    ax_2.set_yticks(np.arange(df.shape[0]) + 0.5)
    ax_2.set_yticklabels(df["Pathway"])

    min_val = perc_amgs_per_sample.min().min()
    max_val = perc_amgs_per_sample.max().max()
    middle_val = (min_val + max_val) / 2

    for i in range(only_samples.shape[0]):
        for j in range(only_samples.shape[1]):
            ax_2.text(
                j + 0.5,
                i + 0.5,
                only_samples.iloc[i, j],
                ha="center",
                va="center",
                color=(
                    "w" if perc_amgs_per_sample.iloc[i, j] > middle_val else "k"
                ),
            )

    ax_3 = fig.add_axes([1, 1, 4 / df.shape[1], 1 / (2 * df.shape[0])])

    fig.colorbar(
        im,
        cax=(ax_3),
        pad=0.05,
        orientation="horizontal",
        label="Proportion of viral scaffolds which include AMGs",
    )

    return fig


def create_amg_plot(
    vibrant_output_dirs: List[str], threads: int
) -> matplotlib.figure.Figure:
    with mp.Pool(threads) as p:
        dataframes = p.map(amg_per_scaffold, vibrant_output_dirs)

    merged_df = reduce(merge_two_dfs, dataframes).sort_values(
        ["Metabolism", "Pathway"], ascending=False
    )

    metabolism_label_df = metabolism_df(merged_df, "KEGG Entry")

    merged_df = merged_df.merge(
        metabolism_label_df[["color"]],
        left_on="Metabolism",
        right_index=True,
    )

    fig = pathway_map(merged_df, metabolism_label_df)

    return fig


def matabolism_pathway_amg_df(vibrant_output_dir: str) -> pd.DataFrame:
    sample = path.basename(vibrant_output_dir).replace("VIBRANT_", "")

    pathway_file = find_pathway_file(vibrant_output_dir)
    amg_counts_file = find_counts_file(vibrant_output_dir)

    pathway_df = pd.read_table(pathway_file)
    amg_counts_df = pd.read_table(amg_counts_file)

    temp_df = pathway_df.rename(
        columns={"Present AMG KOs": "AMG KO", "AMG count": sample}
    ).filter(items=["Metabolism", "Pathway", "AMG KO"], axis="columns")

    temp_df.loc[:, "AMG KO"] = temp_df["AMG KO"].str.split(",")
    # If you try to write the assignment as asdf["AMG KO"] = asdf["AMG KO"].str.split(",")
    # It throws a warning because you are trying to set the value of a copy of a slice
    # It works anyway, but I've used .loc just to be sure

    temp_df = temp_df.explode("AMG KO")

    merged = temp_df.merge(amg_counts_df, on="AMG KO").rename(
        columns={"AMG count": sample}
    )

    return merged


def merge_metabolism_frames(
    left: pd.DataFrame, right: pd.DataFrame
) -> pd.DataFrame:
    return pd.merge(
        left,
        right,
        how="outer",
        on=["Metabolism", "Pathway", "AMG KO", "AMG KO name"],
    ).fillna(0)


def all_metabolism_map(
    df: pd.DataFrame, metabolism_df: pd.DataFrame
) -> matplotlib.figure.Figure:
    only_samples = df.drop(
        columns=[
            "Metabolism",
            "Pathway",
            "AMG KO",
            "AMG KO name",
            "color",
            "y_label",
        ]
    ).astype(int)

    perc_amgs_per_sample = only_samples / only_samples.sum()

    fig, (ax_1, ax_2) = plt.subplots(
        1,
        2,
        figsize=((df.shape[1] + 1) / 2, df.shape[0] / 2),
        gridspec_kw={"width_ratios": (1, df.shape[1])},
        squeeze=True,
    )

    ax_1.pcolormesh(df[["color"]], cmap="Paired_r")
    ax_1.set_yticks(metabolism_df["position"] + 0.5)
    ax_1.set_yticklabels(metabolism_df.index)
    ax_1.get_xaxis().set_visible(False)

    im = ax_2.pcolormesh(
        perc_amgs_per_sample,
        cmap="GnBu",
    )

    ax_2.set_title(
        "AMG copies per sample",
        fontdict={"fontsize": "xx-large"},
    )

    ax_2.xaxis.tick_top()
    ax_2.yaxis.tick_right()

    ax_2.set_xticks(np.arange(only_samples.shape[1]) + 0.5)
    ax_2.set_xticklabels(only_samples.columns, rotation=45, ha="left")

    ax_2.set_yticks(np.arange(df.shape[0]) + 0.5)
    ax_2.set_yticklabels(df["y_label"])

    min_val = perc_amgs_per_sample.min().min()
    max_val = perc_amgs_per_sample.max().max()
    middle_val = (min_val + max_val) / 2

    for i in range(only_samples.shape[0]):
        for j in range(only_samples.shape[1]):
            ax_2.text(
                j + 0.5,
                i + 0.5,
                only_samples.iloc[i, j],
                ha="center",
                va="center",
                color=(
                    "w" if perc_amgs_per_sample.iloc[i, j] > middle_val else "k"
                ),
            )
    ax_3 = fig.add_axes([1, 1, 4 / df.shape[1], 1 / (2 * df.shape[0])])

    fig.colorbar(
        im,
        cax=(ax_3),
        pad=0.05,
        orientation="horizontal",
        label="Proportion of AMG copies in the sample",
    )

    return fig


def create_metabolism_plot(
    vibrant_output_dirs: List[str], threads: Union[int, None]
) -> Tuple[pd.DataFrame, matplotlib.figure.Figure]:
    with mp.Pool(threads) as p:
        dataframes = p.map(matabolism_pathway_amg_df, vibrant_output_dirs)

    merged_df = reduce(merge_metabolism_frames, dataframes).sort_values(
        ["Metabolism", "Pathway", "AMG KO"], ascending=False
    )

    metabolism_label_df = metabolism_df(merged_df, "AMG KO")

    merged_df = merged_df.merge(
        metabolism_label_df["color"],
        left_on="Metabolism",
        right_index=True,
    )
    merged_df["y_label"] = merged_df["AMG KO"] + " | " + merged_df["Pathway"]
    fig = all_metabolism_map(merged_df, metabolism_label_df)

    return merged_df, fig


def main() -> None:
    args = parse_arguments()

    if args.multiple_directories:
        output_directories = find_output_directories(args.input_dir)

        with mp.Pool(args.threads) as p:
            outputs = p.map(parse_single_directory, output_directories)

        multiple_df = pd.DataFrame(dict(outputs))
        multiple_df.to_csv(args.output, sep="\t")

    else:
        output_directories = [args.input_dir]
        parse_single_directory(args.input_dir, args.output)

    amg_plot_path = args.input_dir + "_amg_plot.pdf"
    amg_plot = create_amg_plot(output_directories, args.threads)
    amg_plot.savefig(amg_plot_path, bbox_inches="tight")

    metabolism_plot_path = args.input_dir + "_metabolism_plot.pdf"
    metabolism_tsv_path = args.input_dir + "_metabolism.tsv"
    metabolism_df, metabolism_plot = create_metabolism_plot(
        output_directories, args.threads
    )
    metabolism_plot.savefig(metabolism_plot_path, bbox_inches="tight")
    metabolism_df.to_csv(metabolism_tsv_path, sep="\t", index=False)


if __name__ == "__main__":
    main()
