# This are the cdhit criterias, identity_threshold is the sequence identity threshold with range from float(0>1)
# coverage is the alignment coverage for the shorter sequences
cd-hit-est_criteria:
  identity_threshold: 0.95
  coverage: 0.85
# This represents the cutoff threshold for the checkv quality with options:
# Not-determined, Low, Medium, High, Complete
checkv_threshold: Medium
# The paths to each database location
database_dir:
  checkv: /Some/Path/VirMake/databases/checkv/checkv-db-v1.5
  DRAM: /Some/Path/VirMake/databases/DRAM
  INPHARED: /Some/Path/VirMake/databases/INPHARED
  RefSeq: /Some/Path/VirMake/databases/RefSeq/viral.1.1.genomic.fna
  virsorter2: /Some/Path/VirMake/databases/virsorter2/db
  main_dir: /Some/Path/VirMake/databases
threads: 8
# The VIBRANT sequence cuttoff lenght and if sequences are virom (yes/no)
vibrant_settings:
  cutoff_length: 1000
  is_virome: 'no'
# The virsorter2 sequence cuttoff lenght and minimum score cutoff
virsorter2_settings:
  pass1:
    min_lenght: 3000
    min_score: 0.5
  pass2:
    min_lenght: 1000
    min_score: 0.5
workflow_dirs:
  log_dir: logs/
  profile_dir: profile/
  output_dir: results/
  input_dir: samples/
  working_dir: /Some/Path/VirMake/
# The location to the Sample table
sample_table: /Some/Path/VirMake/samples.tsv
# Below are all resources used when running on cluster.
# change job_type to be the same as partition in SLURM
# Change settings here to suit cluster execution
big_mem: 32000
big_time: 0-13:00:00
job_type:
  big: bigmem
  normal: normal
  small: normal
metaquast_mem: 63000
metaquast_time: 0-24:00:00
normal_mem: 16000
normal_time: 0-06:00:00
small_mem: 8000
small_time: 0-01:00:00
tiny_mem: 1000
tiny_time: 0-00:30:00
vcontact2_mem: 63000
vcontact2_time: 0-24:00:00
